---
language: node_js
node_js:
  - "8.11.0"

sudo: false

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install

script:
  - npm test

notifications:
  email: false
